### ISSUE TITLE
Tips on setting up minimal ltsp server

### ISSUE THREAD

**Issue by greavette** [maxnet/berryterminal#2]
Hello,

I'm not sure where to post questions so i apologize if this isn't the right place.

I want to use berryterminal to connect to a minimal ltsp session.  The ltsp session berryterminal connects to will auto connect using rdesktop to a windows virtual machine.  Basically the ltsp i setup won't be used except for rdesktop.  

Would you have any links or advise you can give me on how to set this up?

Thank you.

**Comment by maxnet** [comment]
Might be easier to run rdesktop on the Pi directly.

**Comment by maxnet** [comment]
Closing old bugs
